language: haskell

ghc:
  - 7.8
  - 7.6

install:
  - cabal update
  - cabal install -j --only-dep --enable-tests --force-reinstalls --reorder-goals

script:
  - cabal configure --enable-tests && cabal build && cabal test
